version: '3.5'

services:
  kafka01:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka01
    container_name: kafka01
    labels:
      NAME: 'kafka01'
    ports:
      - "39092:39092"
    environment:
      CLUSTER_ID: D5hl1DjsSECe1wAAdfOOqQ
      KAFKA_LISTENERS: BROKER://kafka01:19092,EXTERNAL://kafka01:39092,CONTROLLER://kafka01:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka01:19092,EXTERNAL://kafka01:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka01-data:/var/lib/kafka/data
      - ./kafka/update_cluster.sh:/tmp/update_cluster.sh
      - ./kafka/clusterID:/tmp/clusterID
  kafka02:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka02
    container_name: kafka02
    labels:
      NAME: 'kafka02'
    ports:
      - "39093:39093"
    environment:
      CLUSTER_ID: D5hl1DjsSECe1wAAdfOOqQ
      KAFKA_LISTENERS: BROKER://kafka02:19093,EXTERNAL://kafka02:39093,CONTROLLER://kafka02:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka02:19093,EXTERNAL://kafka02:39093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka02-data:/var/lib/kafka/data
  kafka03:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka03
    container_name: kafka03
    labels:
      NAME: 'kafka03'
    ports:
      - "39094:39094"
    environment:
      CLUSTER_ID: D5hl1DjsSECe1wAAdfOOqQ
      KAFKA_LISTENERS: BROKER://kafka03:19094,EXTERNAL://kafka03:39094,CONTROLLER://kafka03:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka03:19094,EXTERNAL://kafka03:39094
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka03-data:/var/lib/kafka/data
networks:
  internal:
volumes:
  kafka01-data:
  kafka02-data:
  kafka03-data: