version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rmq
      - RABBITMQ_DEFAULT_PASS=rabbit
    networks:
      - internal
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    labels:
      NAME: 'rabbitmq'
  hazelcast:
    image: hazelcast/hazelcast:latest
    hostname: hazelcast
    networks:
      - internal
    ports:
      - '5701:5701'
      - '5702:5702'
    environment:
      - HZ_CLUSTERNAME=shareprice
    labels:
      NAME: 'hazelcast'
  hazelcast-management-center:
    image: hazelcast/management-center:latest
    hostname: hcastmanagement
    networks:
      - internal
    ports:
      - '8080:8080'
    environment:
      - MC_DEFAULT_CLUSTER=shareprice
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
  kafka01:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka01
    container_name: kafka01
    labels:
      NAME: 'kafka01'
    networks:
      - internal
    ports:
      - "39092:39092"
    environment:
      CLUSTER_ID: D5hl1DjsSECe1wAAdfOOqQ
      KAFKA_LISTENERS: BROKER://kafka01:19092,EXTERNAL://kafka01:39092,CONTROLLER://kafka01:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka01:19092,EXTERNAL://kafka01:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka01-data:/var/lib/kafka/data
      - ./kafka/update_cluster.sh:/tmp/update_cluster.sh
      - ./kafka/clusterID:/tmp/clusterID
  kafka02:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka02
    container_name: kafka02
    labels:
      NAME: 'kafka02'
    networks:
      - internal
    ports:
      - "39093:39093"
    environment:
      CLUSTER_ID: D5hl1DjsSECe1wAAdfOOqQ
      KAFKA_LISTENERS: BROKER://kafka02:19093,EXTERNAL://kafka02:39093,CONTROLLER://kafka02:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka02:19093,EXTERNAL://kafka02:39093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka02-data:/var/lib/kafka/data
  kafka03:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka03
    container_name: kafka03
    labels:
      NAME: 'kafka03'
    networks:
      - internal
    ports:
      - "39094:39094"
    environment:
      CLUSTER_ID: D5hl1DjsSECe1wAAdfOOqQ
      KAFKA_LISTENERS: BROKER://kafka03:19094,EXTERNAL://kafka03:39094,CONTROLLER://kafka03:9093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka03:19094,EXTERNAL://kafka03:39094
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka03-data:/var/lib/kafka/data
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    labels:
      NAME: "mysql"
    networks:
      internal:
    ports:
      - "3306:3306"
    volumes:
      - /var/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shareprice
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysqlpassword
  drop-off:
    image: ramindur/drop-off-service:2.2.1
    hostname: dropoff01
    container_name: dropoff01
    labels:
      NAME: 'dropoff01'
    networks:
      - internal
    ports:
      - "8090:8090"
networks:
  internal:
volumes:
  kafka01-data:
  kafka02-data:
  kafka03-data:
